site_name: "陽明交大資訊技術服務中心 Wiki"
site_url: https://nycu-it-reg.github.io/docSystem/ # 請替換 YOUR_USERNAME 為你的 GitHub 使用者名稱
#repo_url: https://github.com/nycu-it-reg/docSystem  # 請替換 YOUR_USERNAME 為你的 GitHub 使用者名稱
#repo_name: docSystem
edit_uri: edit/main/docs/ # 允許使用者建議編輯

theme:
  name: material
  language: zh-TW
  favicon: assets/images/favicon.ico
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: 切換至深色模式
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: 切換至淺色模式
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

# Navigation
nav:
  - 首頁: index.md
  - HPC 高速運算平台:
      - hpc/index.md
      - 申請系統:
          - hpc/registration/index.md
      - 基本操作: hpc/basic.md
      - 容器:
          - 認識容器: hpc/container/index.md
          - 建製映像: hpc/container/build-image.md
          - 執行: hpc/container/run.md
          - Nvidia 映像: hpc/container/ngc.md

plugins:
  - search:
      lang:
        - zh
        - en
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh-TW
          default: true
          name: 繁體中文
          build: true
          nav_translations:
            首頁: 首頁
            HPC 高速運算平台: 高速運算平台 (HPC)
            帳號管理: 帳號管理

        - locale: en
          name: English
          build: true
          nav_translations:
            首頁: Home
            HPC 高速運算平台: HPC, High Performance Computing

# Footer customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nycu-it-reg/docSystem # 請替換 YOUR_USERNAME
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:support@it.nycu.edu.tw
      name: 聯絡我們
  generator: false

# Copyright (year will be automatically updated via hooks)
copyright: Copyright &copy; 國立陽明交通大學資訊技術服務中心

# Extra CSS for custom styling
extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/accessibility.css

# Extra JavaScript for enhanced functionality

# Hooks for dynamic content
hooks:
  - hooks/copyright_year.py
